# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyswip import Prolog
from inferenceIngene import pickOne, definition


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(819, 575)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0.455, x2:0, y2:0.426, stop:0 rgba(78, 67, 118, 255), stop:0.755682 rgba(43, 88, 118, 255));\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("\n"
"\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(45, 45, 68);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"\n"
" }\n"
" QScrollBar {\n"
"\n"
"    border: none;\n"
"    background: rgb(45, 45, 68);\n"
"    color: white;\n"
"    border-radius: 20px;\n"
"    background-image: url(:/photos/1_wcEYa9AjnMZxXAau2iuhYw.png);\n"
"\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(80, 80, 122);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: #B37BAC;\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: #D583AB;\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: #B37BAC;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: #D583AB;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color:#B37BAC;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: #D583AB;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(9, -1, 9, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logoFrame = QtWidgets.QFrame(self.centralwidget)
        self.logoFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.logoFrame.setSizeIncrement(QtCore.QSize(0, 0))
        self.logoFrame.setStyleSheet("background-color: transparent;")
        self.logoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoFrame.setObjectName("logoFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.logoFrame)
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.logo = QtWidgets.QLabel(self.logoFrame)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.logo.setFont(font)
        self.logo.setStyleSheet("color: rgb(255, 162, 32);\n"
"background-color: transparent;")
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.verticalLayout_5.addWidget(self.logo, 0, QtCore.Qt.AlignHCenter)
        self.slogan = QtWidgets.QLabel(self.logoFrame)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Light")
        font.setPointSize(9)
        self.slogan.setFont(font)
        self.slogan.setStyleSheet("color: rgb(212, 244, 255);")
        self.slogan.setObjectName("slogan")
        self.verticalLayout_5.addWidget(self.slogan, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.logoFrame)
        self.photo = QtWidgets.QFrame(self.centralwidget)
        self.photo.setMinimumSize(QtCore.QSize(0, 156))
        self.photo.setBaseSize(QtCore.QSize(0, 0))
        self.photo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.photo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.photo.setObjectName("photo")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.photo)
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_6.setSpacing(9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.line = QtWidgets.QFrame(self.photo)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.photo1 = QtWidgets.QLabel(self.photo)
        self.photo1.setStyleSheet("background-color: transparent;")
        self.photo1.setText("")
        self.photo1.setPixmap(QtGui.QPixmap(":/photos/Group 1.png"))
        self.photo1.setScaledContents(False)
        self.photo1.setAlignment(QtCore.Qt.AlignCenter)
        self.photo1.setObjectName("photo1")
        self.verticalLayout_6.addWidget(self.photo1)
        self.verticalLayout.addWidget(self.photo)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Medium")
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background-color: transparent;\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.landingPage = QtWidgets.QWidget()
        self.landingPage.setObjectName("landingPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.landingPage)
        self.verticalLayout_2.setContentsMargins(0, 17, -1, -1)
        self.verticalLayout_2.setSpacing(22)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ps = QtWidgets.QLabel(self.landingPage)
        font = QtGui.QFont()
        font.setFamily("Miriam Mono CLM")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.ps.setFont(font)
        self.ps.setStyleSheet("color:rgb(170, 255, 255)")
        self.ps.setObjectName("ps")
        self.verticalLayout_2.addWidget(self.ps, 0, QtCore.Qt.AlignHCenter)
        self.form = QtWidgets.QFrame(self.landingPage)
        self.form.setStyleSheet("")
        self.form.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.form.setFrameShadow(QtWidgets.QFrame.Raised)
        self.form.setObjectName("form")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.form)
        self.verticalLayout_3.setContentsMargins(9, 0, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("\n"
"background-color: rgb(34, 45, 68);\n"
"\n"
"color: white;\n"
"    ")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -756, 816, 1031))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(37, 0, 37, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.q1 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q1.sizePolicy().hasHeightForWidth())
        self.q1.setSizePolicy(sizePolicy)
        self.q1.setMinimumSize(QtCore.QSize(0, 100))
        self.q1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.q1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.q1.setObjectName("q1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.q1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ques = QtWidgets.QLabel(self.q1)
        self.ques.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Medium")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ques.setFont(font)
        self.ques.setObjectName("ques")
        self.horizontalLayout_4.addWidget(self.ques)
        self.yes = QtWidgets.QRadioButton(self.q1)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates")
        font.setPointSize(8)
        self.yes.setFont(font)
        self.yes.setObjectName("yes")
        self.horizontalLayout_4.addWidget(self.yes, 0, QtCore.Qt.AlignRight)
        self.no = QtWidgets.QRadioButton(self.q1)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates")
        font.setPointSize(8)
        self.no.setFont(font)
        self.no.setStyleSheet("color: rgb(255, 255, 255);")
        self.no.setObjectName("no")
        self.horizontalLayout_4.addWidget(self.no, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.q1)
        self.q2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q2.sizePolicy().hasHeightForWidth())
        self.q2.setSizePolicy(sizePolicy)
        self.q2.setMinimumSize(QtCore.QSize(0, 100))
        self.q2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.q2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.q2.setObjectName("q2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.q2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.ques2 = QtWidgets.QLabel(self.q2)
        self.ques2.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Medium")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ques2.setFont(font)
        self.ques2.setObjectName("ques2")
        self.horizontalLayout_11.addWidget(self.ques2)
        self.yes2 = QtWidgets.QRadioButton(self.q2)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates")
        self.yes2.setFont(font)
        self.yes2.setObjectName("yes2")
        self.horizontalLayout_11.addWidget(self.yes2, 0, QtCore.Qt.AlignRight)
        self.no2 = QtWidgets.QRadioButton(self.q2)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates")
        self.no2.setFont(font)
        self.no2.setObjectName("no2")
        self.horizontalLayout_11.addWidget(self.no2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.q2)
        self.q3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q3.sizePolicy().hasHeightForWidth())
        self.q3.setSizePolicy(sizePolicy)
        self.q3.setMinimumSize(QtCore.QSize(0, 100))
        self.q3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.q3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.q3.setObjectName("q3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.q3)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.ques3 = QtWidgets.QLabel(self.q3)
        self.ques3.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Medium")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ques3.setFont(font)
        self.ques3.setObjectName("ques3")
        self.horizontalLayout_12.addWidget(self.ques3)
        self.yes3 = QtWidgets.QRadioButton(self.q3)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates")
        self.yes3.setFont(font)
        self.yes3.setObjectName("yes3")
        self.horizontalLayout_12.addWidget(self.yes3, 0, QtCore.Qt.AlignRight)
        self.no3 = QtWidgets.QRadioButton(self.q3)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates")
        self.no3.setFont(font)
        self.no3.setObjectName("no3")
        self.horizontalLayout_12.addWidget(self.no3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.q3)
        self.q4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q4.sizePolicy().hasHeightForWidth())
        self.q4.setSizePolicy(sizePolicy)
        self.q4.setMinimumSize(QtCore.QSize(0, 100))
        self.q4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.q4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.q4.setObjectName("q4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.q4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ques4 = QtWidgets.QLabel(self.q4)
        self.ques4.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Medium")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ques4.setFont(font)
        self.ques4.setObjectName("ques4")
        self.horizontalLayout_7.addWidget(self.ques4)
        self.yes4 = QtWidgets.QRadioButton(self.q4)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates")
        self.yes4.setFont(font)
        self.yes4.setObjectName("yes4")
        self.horizontalLayout_7.addWidget(self.yes4, 0, QtCore.Qt.AlignRight)
        self.no4 = QtWidgets.QRadioButton(self.q4)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates")
        self.no4.setFont(font)
        self.no4.setObjectName("no4")
        self.horizontalLayout_7.addWidget(self.no4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.q4)
        self.q5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q5.sizePolicy().hasHeightForWidth())
        self.q5.setSizePolicy(sizePolicy)
        self.q5.setMinimumSize(QtCore.QSize(0, 100))
        self.q5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.q5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.q5.setObjectName("q5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.q5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ques5 = QtWidgets.QLabel(self.q5)
        self.ques5.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Medium")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ques5.setFont(font)
        self.ques5.setObjectName("ques5")
        self.horizontalLayout_6.addWidget(self.ques5)
        self.yes5 = QtWidgets.QRadioButton(self.q5)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates")
        self.yes5.setFont(font)
        self.yes5.setObjectName("yes5")
        self.horizontalLayout_6.addWidget(self.yes5, 0, QtCore.Qt.AlignRight)
        self.no5 = QtWidgets.QRadioButton(self.q5)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates")
        self.no5.setFont(font)
        self.no5.setObjectName("no5")
        self.horizontalLayout_6.addWidget(self.no5, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.q5)
        self.q1_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q1_2.sizePolicy().hasHeightForWidth())
        self.q1_2.setSizePolicy(sizePolicy)
        self.q1_2.setMinimumSize(QtCore.QSize(0, 100))
        self.q1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.q1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.q1_2.setObjectName("q1_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.q1_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ques6 = QtWidgets.QLabel(self.q1_2)
        self.ques6.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Medium")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ques6.setFont(font)
        self.ques6.setObjectName("ques6")
        self.horizontalLayout_5.addWidget(self.ques6)
        self.yes6 = QtWidgets.QRadioButton(self.q1_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates")
        self.yes6.setFont(font)
        self.yes6.setObjectName("yes6")
        self.horizontalLayout_5.addWidget(self.yes6, 0, QtCore.Qt.AlignRight)
        self.no6 = QtWidgets.QRadioButton(self.q1_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates")
        self.no6.setFont(font)
        self.no6.setObjectName("no6")
        self.horizontalLayout_5.addWidget(self.no6, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.q1_2)
        self.q7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q7.sizePolicy().hasHeightForWidth())
        self.q7.setSizePolicy(sizePolicy)
        self.q7.setMinimumSize(QtCore.QSize(0, 100))
        self.q7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.q7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.q7.setObjectName("q7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.q7)
        self.horizontalLayout_8.setContentsMargins(-1, -1, 21, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ques7 = QtWidgets.QLabel(self.q7)
        self.ques7.setMinimumSize(QtCore.QSize(481, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Medium")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ques7.setFont(font)
        self.ques7.setObjectName("ques7")
        self.horizontalLayout_8.addWidget(self.ques7)
        self.comboBox7 = QtWidgets.QComboBox(self.q7)
        self.comboBox7.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox7.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox7.setFont(font)
        self.comboBox7.setObjectName("comboBox7")
        self.comboBox7.addItem("")
        self.comboBox7.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox7)
        self.verticalLayout_4.addWidget(self.q7)
        self.q8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q8.sizePolicy().hasHeightForWidth())
        self.q8.setSizePolicy(sizePolicy)
        self.q8.setMinimumSize(QtCore.QSize(0, 100))
        self.q8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.q8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.q8.setObjectName("q8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.q8)
        self.horizontalLayout_10.setContentsMargins(-1, -1, 21, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.ques8 = QtWidgets.QLabel(self.q8)
        self.ques8.setMinimumSize(QtCore.QSize(481, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Medium")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ques8.setFont(font)
        self.ques8.setObjectName("ques8")
        self.horizontalLayout_10.addWidget(self.ques8)
        self.comboBox8 = QtWidgets.QComboBox(self.q8)
        self.comboBox8.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox8.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox8.setFont(font)
        self.comboBox8.setObjectName("comboBox8")
        self.comboBox8.addItem("")
        self.comboBox8.addItem("")
        self.comboBox8.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox8)
        self.verticalLayout_4.addWidget(self.q8)
        self.q9 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q9.sizePolicy().hasHeightForWidth())
        self.q9.setSizePolicy(sizePolicy)
        self.q9.setMinimumSize(QtCore.QSize(0, 100))
        self.q9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.q9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.q9.setObjectName("q9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.q9)
        self.horizontalLayout_9.setContentsMargins(-1, -1, 21, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ques9 = QtWidgets.QLabel(self.q9)
        self.ques9.setMinimumSize(QtCore.QSize(481, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Medium")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ques9.setFont(font)
        self.ques9.setObjectName("ques9")
        self.horizontalLayout_9.addWidget(self.ques9)
        self.comboBox9 = QtWidgets.QComboBox(self.q9)
        self.comboBox9.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox9.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox9.setFont(font)
        self.comboBox9.setObjectName("comboBox9")
        self.comboBox9.addItem("")
        self.comboBox9.addItem("")
        self.comboBox9.addItem("")
        self.comboBox9.addItem("")
        self.comboBox9.addItem("")
        self.comboBox9.addItem("")
        self.comboBox9.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox9)
        self.verticalLayout_4.addWidget(self.q9)
        self.btnFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.btnFrame.setMinimumSize(QtCore.QSize(0, 68))
        self.btnFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btnFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnFrame.setObjectName("btnFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.btnFrame)
        self.verticalLayout_7.setContentsMargins(200, -1, 200, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton = QtWidgets.QPushButton(self.btnFrame)
        self.pushButton.clicked.connect(self.showResults)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(201, 37))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    /* Default state */\n"
"    background-color:qlineargradient(spread:pad, x1:0.5345, y1:0, x2:0.557, y2:1, stop:0 rgba(255, 162, 32, 255), stop:0.755682 rgba(213, 132, 26, 255)); /* Set the desired color */\n"
"    border-radius: 4px; /* Set the desired border radius */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Hover state */\n"
"    background-color: rgb(255, 158, 32); /* Set the desired color */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* Clicked state */\n"
"    background-color: rgb(167, 103, 20); /* Set the desired color */\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_7.addWidget(self.pushButton)
        self.verticalLayout_4.addWidget(self.btnFrame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout_2.addWidget(self.form)
        self.stackedWidget.addWidget(self.landingPage)
        self.resultPage = QtWidgets.QWidget()
        self.resultPage.setObjectName("resultPage")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.resultPage)
        self.verticalLayout_10.setSpacing(7)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.keyWordsFrame = QtWidgets.QFrame(self.resultPage)
        self.keyWordsFrame.setMinimumSize(QtCore.QSize(100, 100))
        self.keyWordsFrame.setStyleSheet("color: rgb(255, 255, 255);")
        self.keyWordsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.keyWordsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.keyWordsFrame.setObjectName("keyWordsFrame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.keyWordsFrame)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.keyLabel = QtWidgets.QLabel(self.keyWordsFrame)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates ExtraBold")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.keyLabel.setFont(font)
        self.keyLabel.setObjectName("keyLabel")
        self.horizontalLayout_13.addWidget(self.keyLabel)
        self.keyWords = QtWidgets.QFrame(self.keyWordsFrame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.keyWords.setFont(font)
        self.keyWords.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.keyWords.setFrameShadow(QtWidgets.QFrame.Raised)
        self.keyWords.setObjectName("keyWords")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.keyWords)
        self.horizontalLayout.setContentsMargins(18, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.a1 = QtWidgets.QLabel(self.keyWords)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(8)
        self.a1.setFont(font)
        self.a1.setObjectName("a1")
        self.horizontalLayout.addWidget(self.a1, 0, QtCore.Qt.AlignLeft)
        self.a2 = QtWidgets.QLabel(self.keyWords)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(8)
        self.a2.setFont(font)
        self.a2.setObjectName("a2")
        self.horizontalLayout.addWidget(self.a2, 0, QtCore.Qt.AlignLeft)
        self.a3 = QtWidgets.QLabel(self.keyWords)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(8)
        self.a3.setFont(font)
        self.a3.setObjectName("a3")
        self.horizontalLayout.addWidget(self.a3, 0, QtCore.Qt.AlignLeft)
        self.a4 = QtWidgets.QLabel(self.keyWords)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(8)
        self.a4.setFont(font)
        self.a4.setObjectName("a4")
        self.horizontalLayout.addWidget(self.a4, 0, QtCore.Qt.AlignLeft)
        self.a5 = QtWidgets.QLabel(self.keyWords)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(8)
        self.a5.setFont(font)
        self.a5.setObjectName("a5")
        self.horizontalLayout.addWidget(self.a5, 0, QtCore.Qt.AlignHCenter)
        self.a6 = QtWidgets.QLabel(self.keyWords)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(8)
        self.a6.setFont(font)
        self.a6.setObjectName("a6")
        self.horizontalLayout.addWidget(self.a6, 0, QtCore.Qt.AlignHCenter)
        self.a7 = QtWidgets.QLabel(self.keyWords)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(8)
        self.a7.setFont(font)
        self.a7.setObjectName("a7")
        self.horizontalLayout.addWidget(self.a7, 0, QtCore.Qt.AlignHCenter)
        self.a8 = QtWidgets.QLabel(self.keyWords)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(8)
        self.a8.setFont(font)
        self.a8.setObjectName("a8")
        self.horizontalLayout.addWidget(self.a8, 0, QtCore.Qt.AlignHCenter)
        self.a9 = QtWidgets.QLabel(self.keyWords)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(8)
        self.a9.setFont(font)
        self.a9.setObjectName("a9")
        self.horizontalLayout.addWidget(self.a9, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_13.addWidget(self.keyWords)
        self.verticalLayout_10.addWidget(self.keyWordsFrame, 0, QtCore.Qt.AlignHCenter)
        self.resultLang = QtWidgets.QFrame(self.resultPage)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Medium")
        self.resultLang.setFont(font)
        self.resultLang.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.resultLang.setFrameShadow(QtWidgets.QFrame.Raised)
        self.resultLang.setObjectName("resultLang")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.resultLang)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lang = QtWidgets.QLabel(self.resultLang)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Black")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.lang.setFont(font)
        self.lang.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lang.setStyleSheet("color: rgb(255, 162, 32);")
        self.lang.setFrameShape(QtWidgets.QFrame.Box)
        self.lang.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lang.setObjectName("lang")
        self.verticalLayout_8.addWidget(self.lang, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addWidget(self.resultLang)
        self.definitionAndOtherFrame = QtWidgets.QFrame(self.resultPage)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Medium")
        font.setPointSize(9)
        self.definitionAndOtherFrame.setFont(font)
        self.definitionAndOtherFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.definitionAndOtherFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.definitionAndOtherFrame.setObjectName("definitionAndOtherFrame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.definitionAndOtherFrame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.definitionField = QtWidgets.QPlainTextEdit(self.definitionAndOtherFrame)
        self.definitionField.setMinimumSize(QtCore.QSize(700, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.definitionField.setFont(font)
        self.definitionField.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.definitionField.setStyleSheet("color:white;\n"
"    /* Set the desired text alignment */\n"
"    qproperty-alignment: AlignCenter;\n"
"\n"
"\n"
"")
        self.definitionField.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.definitionField.setLineWidth(0)
        self.definitionField.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.definitionField.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.definitionField.setReadOnly(True)
        self.definitionField.setCenterOnScroll(False)
        self.definitionField.setObjectName("definitionField")
        self.verticalLayout_9.addWidget(self.definitionField, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.otherLangFrame = QtWidgets.QFrame(self.definitionAndOtherFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otherLangFrame.sizePolicy().hasHeightForWidth())
        self.otherLangFrame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Medium")
        self.otherLangFrame.setFont(font)
        self.otherLangFrame.setStyleSheet("color: rgb(170, 255, 255);")
        self.otherLangFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.otherLangFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.otherLangFrame.setObjectName("otherLangFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.otherLangFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.titre = QtWidgets.QLabel(self.otherLangFrame)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates ExtraBold")
        font.setPointSize(9)
        self.titre.setFont(font)
        self.titre.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.titre.setObjectName("titre")
        self.horizontalLayout_3.addWidget(self.titre)
        self.otherLangs = QtWidgets.QLabel(self.otherLangFrame)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates ExtraBold")
        font.setPointSize(9)
        self.otherLangs.setFont(font)
        self.otherLangs.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.otherLangs.setObjectName("otherLangs")
        self.horizontalLayout_3.addWidget(self.otherLangs, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_9.addWidget(self.otherLangFrame, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addWidget(self.definitionAndOtherFrame, 0, QtCore.Qt.AlignTop)
        self.goBackBtn = QtWidgets.QPushButton(self.resultPage)
        self.goBackBtn.clicked.connect(lambda : self.stackedWidget.setCurrentIndex(0))
        self.goBackBtn.setMinimumSize(QtCore.QSize(89, 29))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates ExtraBold")
        font.setPointSize(9)
        self.goBackBtn.setFont(font)
        self.goBackBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.goBackBtn.setStyleSheet("QPushButton {\n"
"    /* Default state */\n"
"    background-color:qlineargradient(spread:pad, x1:0.5345, y1:0, x2:0.557, y2:1, stop:0 rgba(255, 162, 32, 255), stop:0.755682 rgba(213, 132, 26, 255)); /* Set the desired color */\n"
"    border-radius: 4px; /* Set the desired border radius */\n"
"color:white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Hover state */\n"
"    background-color: rgb(255, 158, 32); /* Set the desired color */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* Clicked state */\n"
"    background-color: rgb(167, 103, 20); /* Set the desired color */\n"
"}\n"
"")
        self.goBackBtn.setObjectName("goBackBtn")
        self.verticalLayout_10.addWidget(self.goBackBtn, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.resultPage)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logo.setText(_translate("MainWindow", "NEXT STEP"))
        self.slogan.setText(_translate("MainWindow", "Your guide for your programming journey."))
        self.ps.setText(_translate("MainWindow", "\"PS: When you choose, you must pick ONLY one choice\""))
        self.ques.setText(_translate("MainWindow", "Would you prefer a programming language that is easy to use? "))
        self.yes.setText(_translate("MainWindow", "Yes"))
        self.no.setText(_translate("MainWindow", "No"))
        self.ques2.setText(_translate("MainWindow", "Are you interested in a language with a large community? "))
        self.yes2.setText(_translate("MainWindow", "Yes"))
        self.no2.setText(_translate("MainWindow", "No"))
        self.ques3.setText(_translate("MainWindow", "Do you prioritize high performance in a programming language? "))
        self.yes3.setText(_translate("MainWindow", "Yes"))
        self.no3.setText(_translate("MainWindow", "No"))
        self.ques4.setText(_translate("MainWindow", "Do you prefer open-source languages?"))
        self.yes4.setText(_translate("MainWindow", "Yes"))
        self.no4.setText(_translate("MainWindow", "No"))
        self.ques5.setText(_translate("MainWindow", "Do you value strong security features in a PL? "))
        self.yes5.setText(_translate("MainWindow", "Yes"))
        self.no5.setText(_translate("MainWindow", "No"))
        self.ques6.setText(_translate("MainWindow", "Do you want a language that is easy to maintain? "))
        self.yes6.setText(_translate("MainWindow", "Yes"))
        self.no6.setText(_translate("MainWindow", "No"))
        self.ques7.setText(_translate("MainWindow", "What type of programming language are you looking for?"))
        self.comboBox7.setItemText(0, _translate("MainWindow", "Compiled"))
        self.comboBox7.setItemText(1, _translate("MainWindow", "Interpreted"))
        self.ques8.setText(_translate("MainWindow", "What is your level of programming expertise?"))
        self.comboBox8.setItemText(0, _translate("MainWindow", "Beginner"))
        self.comboBox8.setItemText(1, _translate("MainWindow", "Intermediate "))
        self.comboBox8.setItemText(2, _translate("MainWindow", "Expert"))
        self.ques9.setText(_translate("MainWindow", "In which specific domain do you plan to use this  PL? "))
        self.comboBox9.setItemText(0, _translate("MainWindow", "General purpose"))
        self.comboBox9.setItemText(1, _translate("MainWindow", "Front-end web development "))
        self.comboBox9.setItemText(2, _translate("MainWindow", "Back-end web development "))
        self.comboBox9.setItemText(3, _translate("MainWindow", "Data science"))
        self.comboBox9.setItemText(4, _translate("MainWindow", "Desktop development"))
        self.comboBox9.setItemText(5, _translate("MainWindow", "Mobile development"))
        self.comboBox9.setItemText(6, _translate("MainWindow", "Game development"))
        self.pushButton.setText(_translate("MainWindow", "Discover languages"))
        self.keyLabel.setText(_translate("MainWindow", "Key words : "))
        self.a1.setText(_translate("MainWindow", ""))
        self.a2.setText(_translate("MainWindow", ""))
        self.a3.setText(_translate("MainWindow", ""))
        self.a4.setText(_translate("MainWindow", ""))
        self.a5.setText(_translate("MainWindow", ""))
        self.a6.setText(_translate("MainWindow", ""))
        self.a7.setText(_translate("MainWindow", ""))
        self.a8.setText(_translate("MainWindow", ""))
        self.a9.setText(_translate("MainWindow", "TextLabel"))
        self.lang.setText(_translate("MainWindow", "Python Language"))
        self.definitionField.setPlainText(_translate("MainWindow", "adlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjladlfasdfhasdjfhjl"))
        self.titre.setText(_translate("MainWindow", "Other recommeded Languages : "))
        self.otherLangs.setText(_translate("MainWindow", "/"))
        self.goBackBtn.setText(_translate("MainWindow", "Go back"))
        
    def showResults(self):
        selectedFeatures = []
        if self.yes.isChecked(): selectedFeatures.append("easy_to_use")
        if self.yes2.isChecked(): selectedFeatures.append("big_community")
        if self.yes3.isChecked(): selectedFeatures.append("high_performance")
        if self.yes4.isChecked(): selectedFeatures.append("open_source")
        if self.yes5.isChecked(): selectedFeatures.append("high_security")
        if self.yes6.isChecked(): selectedFeatures.append("easy_to_maintain")
        typeLang = ["compiled", "interpreted"]
        indexType = self.comboBox7.currentIndex()
        selectedFeatures.append(typeLang[indexType])
        levelUser = ["beginner_level", "intermediate_level", "expert_level"]
        indexLevel = self.comboBox8.currentIndex()
        selectedFeatures.append(levelUser[indexLevel])
        areas = ["general_purpose", "frontend_web_development", "backend_web_development", "data_science", "desktop_development", "mobile_development", "game_development"]
        indexArea = self.comboBox9.currentIndex()
        selectedFeatures.append(areas[indexArea])
        
        #Change the page
        self.stackedWidget.setCurrentIndex(1)
        
        #Consult the prolog file
        prl = Prolog()
        prl.consult('newKB.pl')
        
        #Create the prolog query
        query = f"recommendLanguage({str(selectedFeatures)}, Language)"
        
        #Get the result
        result = list(prl.query(query))
        
        #Get the list of all recommended languages
        languages = [solution["Language"] for solution in result if "Language" in solution]

        #Show the selected features
        for feature in selectedFeatures:
                if feature == "easy_to_use" : self.a1.setText("Easy to use, ")
                if feature == "big_community" : self.a2.setText("Big community, ")
                if feature == "high_performance" : self.a3.setText("High performance, ")
                if feature == "open_source" : self.a4.setText("Open source, ")
                if feature == "high_security" : self.a5.setText("High security, ")
                if feature == "easy_to_maintain" : self.a6.setText("Easy to maintain, ")
        self.a7.setText(typeLang[indexType].replace("_", " ").capitalize() + ", ")
        self.a8.setText(levelUser[indexLevel].replace("_", " ").capitalize() + ", ")
        self.a9.setText(areas[indexArea].replace("_", " ").capitalize())
        
        other = "/"
        if languages: #If at least one language was found
            #Get the final language
            final = pickOne(languages, selectedFeatures[-1])
            self.lang.setText(final.capitalize())
            
            #Get the definition of the final language
            defFinal = definition(final)
            self.definitionField.setPlainText(defFinal)

            #Get the frameworks if web developement is selected
            if indexArea in [1, 2]:
                            feature = "frontend_web_development" if indexArea == 1 else "backend_web_development"
                            for language in languages:
                                                            query = f"recommendFramework(Framework, {language}, {feature})" 

                                                            result = list(prl.query(query))

                                                            frameworks = [solution["Framework"] for solution in result if "Framework" in solution]
                            #Show the frameworks
                            self.titre.setText("Recommended frameworks : ")
                            other = ""
                            for framework in frameworks:
                                other += framework.capitalize() + " - "
                            self.otherLangs.setText(other[:-3])
            else:
                #Show the other recommended languages
                if len(languages) > 1:
                    other = ""
                    for language in languages:
                        other += language.capitalize() + " - " if language != final else ''
                    self.otherLangs.setText(other[:-3])
                        
            

        else:
            #If no language was found
            self.lang.setText("No language found!")
            self.definitionField.setPlainText("""I'm so sorry! There is no language in my knowledge base that satisfies the all the features you introduced to me beforehead. Please re-fill the form. If it's still the same, please contact an expert.""")
            self.otherLangs.setText(other)
        
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
